version: "3.7"
services:
    php:
        build:
            context: ${SERVICES_DIR}/php
            args:
                # PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
                PHP_VERSION: php:${PHP_VERSION}-fpm
                PHP_EXTENSIONS: ${PHP_EXTENSIONS}
                CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
                TZ: "$TZ"
        container_name: php
        volumes:
            - ${PWD}/${SERVICES_DIR}/${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
            # php-fpm 的配置
            - ${PWD}/${SERVICES_DIR}/${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/zz-docker.conf:rw
            # 挂载宿主机 socket 目录，因为 nginx 服务也需要访问
            - ${PWD}/${DATA_DIR}/php/php_fpm/sock:/run/php/
            - ${PWD}/${DATA_DIR}/${PHP_LOG_DIR}:/var/log/php
            # # 因flask_app會執行php程式，故須掛載進data
            # - php-exe:/usr/local/bin

            # 需將有包含php的html一併掛載進php-fpm service內才能順利抓取php file
            - api-html:/var/www/html/API:rw
            - web-html:/var/www/html/WEB:rw

            - paas-dashboard:/var/www/spdpaas/src/dashboard:rw
        # entrypoint: "./crons.sh"
        restart: always
        environment:
            TZ: "$TZ"
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8

    nginx:
        build:
            context: ${SERVICES_DIR}/nginx/web
            args:
                TZ: "$TZ"
        # image: nginx
        container_name: nginx_web
        ports:
            - ${NGINX_HTTP_HOST_PORT}:80
            - ${NGINX_HTTPS_HOST_PORT}:443
        volumes:
            - ${PWD}/${SERVICES_DIR}/${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
            - ${PWD}/${SERVICES_DIR}/${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:rw

            - web-html:/var/www/html/WEB:rw

            - ${PWD}/${DATA_DIR}/${NGINX_LOG_DIR}/web:/var/log/nginx/:rw

            # link php-fpm sock
            - ${PWD}/${DATA_DIR}/php/php_fpm/sock:/run/php/

            # - ${DATA_DIR}/certbot/conf:/etc/letsencrypt
            # - ${DATA_DIR}/certbot/var:/var/lib/letsencrypt
            - ${PWD}/${SERVICES_DIR}/${NGINX_SSL_CERTIFICATE_DIR}:/etc/nginx/ssl:rw

            # - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
            # - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
        restart: always
        environment:
            TZ: "$TZ"
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8
    
    nginx_api:
        build:
            context: ${SERVICES_DIR}/nginx/api
            args:
                TZ: "$TZ"
        # image: nginx
        container_name: nginx_api
        ports:
            - ${NGINX_UWASI_HOST_PORT}:3687
        volumes:
            - ${PWD}/${SERVICES_DIR}/${NGINX_API_CONFD_DIR}:/etc/nginx/templates
            # - ${PWD}/${SERVICES_DIR}/${NGINX_API_CONFD_DIR}:/etc/nginx/conf.d/:rw
            - ${PWD}/${SERVICES_DIR}/${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
            - ${PWD}/${DATA_DIR}/${NGINX_LOG_DIR}/api:/var/log/nginx/:rw

            # - ${DATA_DIR}/certbot/conf:/etc/letsencrypt
            # - ${DATA_DIR}/certbot/var:/var/lib/letsencrypt
            - ${PWD}/${SERVICES_DIR}/${NGINX_SSL_CERTIFICATE_DIR}:/etc/nginx/ssl:rw
            
            # - ${PWD}/${DATA_DIR}/${UWSGI_SOCK_DIR}:/run/uwsgi/
            # - paas-uwsgi-sock:/run/uwsgi/

            # - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
            # - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro

            # link php-fpm sock
            - ${PWD}/${DATA_DIR}/php/php_fpm/sock:/run/php/

            - api-html:/var/www/html/API:rw
            - paas-dashboard:/var/www/spdpaas/src/dashboard:rw

        restart: always
        environment:
            TZ: "$TZ"
            # - UWSGI_PORT=${FLASK_PORT}
            UWSGI_PORT: ${FLASK_PORT}
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8
        command:
            [
                "/bin/sh",
                "-c",
                "envsubst '$$UWSGI_PORT' < /etc/nginx/templates/spdpaas_nginx.conf.template > /etc/nginx/conf.d/spdpaas_nginx.conf && exec nginx -g 'daemon off;'",
            ]
        depends_on:
            - flask_app
        links:
            - flask_app
    
    flask_app:
        build:
            context: ${SERVICES_DIR}/flask
            args:
                TZ: "$TZ"
        container_name: flask_app
        # user: www-data
        # ports:
        #     - 3688:3688
        expose:
            - ${FLASK_PORT}
        volumes:
            - ./wait-for-it.sh:/wait-for-it.sh
            # - ${PWD}/${DATA_DIR}/${UWSGI_LOG_DIR}:/var/log/uwsgi/:rw
            # - ${PWD}/${DATA_DIR}/${FLASK_LOG_DIR}:/var/www/spdpaas/log/:ro

            # - php-exe:/usr/local/bin/php/

            # - ${PWD}/${DATA_DIR}/${UWSGI_SOCK_DIR}:/var/www/spdpaas/run/
            # - paas-uwsgi-sock:/var/www/spdpaas/run/
            - paas-data:/var/www/spdpaas/src/
            - api-html:/var/www/html/API:rw
        command:
            [
                "/bin/sh",
                "-c",
                "/wait-for-it.sh mysql:3306 postgres:5432 redis:6379 -t 10 -- uwsgi -i spdpaas_uwsgi.ini",
            ]
        sysctls:
            - net.core.somaxconn=32678
        restart: always
        environment:
            TZ: "$TZ"
            UWSGI_PORT: ${FLASK_PORT}
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8
        depends_on:
            - redis
            - postgres
            - mysql
            - php
        links:
            - redis
            - postgres
            - mysql

    # certbot:
    #     image: certbot/certbot:latest
    #     command: certonly --webroot --register-unsafely-without-email --webroot-path=/var/www/certbot --agree-tos  -d spdpaas.com -d www.spdpaas.com
    #     volumes:
    #         - ${DATA_DIR}/certbot/conf:/etc/letsencrypt
    #         - ${DATA_DIR}/certbot/var:/var/lib/letsencrypt
    #         - ${DATA_DIR}/certbot/log:/var/log/letsencrypt
    #         - ${DATA_DIR}/certbot/data:/var/www/certbot

    redis:
        image: redis
        container_name: redis
        ports:
            - ${REDIS_HOST_PORT}:6379
        # expose:
        #     - ${REDIS_HOST_PORT}
        volumes:
            - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
            - ${PWD}/${DATA_DIR}/redis:/data/:rw
        restart: always
        entrypoint: ["redis-server", "/etc/redis.conf"]
        environment:
            TZ: "$TZ"
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8

    postgres:
        image: postgres
        container_name: postgres
        # ports:
            # - ${POSTGRES_HOST_PORT}:5432
        expose:
            - ${POSTGRES_HOST_PORT}
        volumes:
            - ${POSTGRES_CONF_FILE}:/etc/postgresql/postgresql.conf:ro
            - ${POSTGRES_HBA_CONF_FILE}:/etc/postgresql/pg_hba.conf:ro
            - ${PWD}/${SERVICES_DIR}/postgres/initdb.d:/docker-entrypoint-initdb.d
            - ${PWD}/${DATA_DIR}/postgres:/var/lib/postgresql/data:rw
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            TZ: "$TZ"
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8
                
    mysql:
        image: mariadb:${MARIADB_VERSION}
        container_name: mysql
        # ports:
        #     - ${MYSQL_HOST_PORT}:3306
        expose:
            - ${MYSQL_HOST_PORT}
        volumes:
            - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/:ro
            - ${PWD}/${DATA_DIR}/mysql:/var/lib/mysql/:rw
            - ${PWD}/${SERVICES_DIR}/mysql/initdb.d:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            # MYSQL_USER: ${MYSQL_USER}
            # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: "$TZ"
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8

    celeryworker:
        build:
            context: ${PWD}/${SERVICES_DIR}/celery
            args:
                TZ: "$TZ"
        container_name: celeryworker
        volumes:
            # - ./wait-for-it.sh:/wait-for-it.sh
            - ${PWD}/${DATA_DIR}/${CELERY_LOG_DIR}:/var/log/celery/:rw
            - ${PWD}/${SERVICES_DIR}/flask/www/spdpaas/src/app/globalvar.py:/var/app/globalvar.py:ro
        # command:
        #     [
        #         "/bin/sh",
        #         "-c",
        #         "/wait-for-it.sh redis:6379 postgres:5432 -t 5 -- celery -A celeryWorker worker --pidfile=/var/run/worker.pid --loglevel=ERROR --logfile=/var/log/celery/worker.log -c 1000 -P gevent -O fair",
        #     ]
        restart: always
        environment:
            TZ: "$TZ"
            # LC_ALL: en_US.UTF-8
            LANG: C.UTF-8
        depends_on:
            - redis
            - postgres
        links:
            - redis
            - postgres

    # worker2:
    #     build:
    #         context: ${SERVICES_DIR}/celery
    #         args:
    #             TZ: "$TZ"
    #     volumes:
    #         - ./wait-for-it.sh:/wait-for-it.sh
    #         - ${DATA_DIR}/${CELERY_LOG_DIR}:/var/log/celery/:rw
    #     command:
    #         [
    #             "/bin/sh",
    #             "-c",
    #             "/wait-for-it.sh redis:6379 -t 5 -- celery -A celeryWorker worker --pidfile=/var/run/worker2.pid --loglevel=debug --logfile=/var/log/celery/worker2.log -c 1000 -P gevent -O fair",
    #         ]
    #     depends_on:
    #         - redis
    #     links:
    #         - redis
    #         - postgres

volumes:
    paas-data:
        # external: true
        name: paas-data
    web-html:
        name: web-html
    api-html:
        name: api-html
    paas-dashboard:
        name: paas-dashboard
    # php-exe:
    #     name: php-exe