version: "3.7"
services:

  # flask_app:
  #   build: './flask_app'
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - rabbit
  #     - mongodb_container

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: super

  simple_worker:
    build: './simple_worker'
    user: nobody
    depends_on:
      - rabbit
      - flask_app
      - mongodb_container
